# the intended target is a raspbery pi 5 cluster (linux)
FROM ubuntu:22.04 AS builder

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
	ca-certificates \
	libsqlite3-dev \
	make \
	g++ \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Makefile LICENSE README.md ./
COPY include/ include/
COPY src/ src/
COPY tables/ tables/

# the multi program defined in the Makefile
RUN make multi

FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends libsqlite3-0 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/bin/multi_solver ./bin/solver
COPY --from=builder /app/tables/ ./tables/

RUN mkdir -p solve_logs
VOLUME /app/solve_logs

ENTRYPOINT ["./bin/solver"]