//this program handles solving cube(s) with solve(vector<int>, Cube&) or solveWrapper(vector<Cube>&)
//uses the tables generated by Tables.cpp and indexers in Cube.cpp
//currently implements Kociemba's 2 phase algorithm via IDA* and heuristics tables of 
//edge orientation combined with corner orientation and phase 1 e slice locations and
//corner locations combined with e slice locations and edge locations combined with e slice locations

#pragma once

#include "Cube.h"
#include "Tables.h"

#include <algorithm>
#include <chrono>

using namespace std;

//number of moves used to generate tables in each phase
constexpr size_t NUM_P1_MOVES = 18;
constexpr size_t NUM_P2_MOVES = 10;

//these will be used for pruning during IDA*
extern size_t p1MoveGroup[NUM_P1_MOVES];
extern size_t p2MoveGroup[NUM_P2_MOVES];

//used to track solution length
extern uint8_t solution_len;
extern uint8_t solution2_len;

//used to trac exploration expansion
extern uint64_t p1counter;
extern uint64_t p2counter;

class Solver
{
	public:
		static void initializeSolver();
		
		static bool solveWrapper(vector<Cube>& cubes);
		static bool solve(vector<int>& solutions, Cube& cube);
		
		static void phase1SolverWrapper(vector<int>& solutions, Cube& cube);
		static int phase1Solver(vector<int>& solutions, int max_cost, int curr_cost, uint16_t eoKey, uint16_t coKey, uint16_t eKey, size_t prevMove);
		
		static void phase2SolverWrapper(vector<int>& solutions, Cube& cube);
		static int phase2Solver(vector<int>& solutions, int max_cost, int curr_cost, uint16_t elKey, uint16_t clKey, uint8_t eKey, size_t prevMove);
};